# Generated by Django 5.2.1 on 2025-05-20 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='total_copies',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
