# Generated by Django 5.2.1 on 2025-08-09 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_book_total_copies'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='available_copies',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
